#ifndef __hexray__
#define __hexray__

#pragma once

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"


#include <vector>
#include <string>

#define HEXRAY_COLS         32
#define HEXRAY_DEF_STEPS    1  // step to 1, 2, or 4



class HexRay
{
	public:
        // Constructor: Initializes the object when it is created
		HexRay();

        // Destructor
		virtual ~HexRay();

        std::vector<char> get_raw(std::string input_file_path);
        void build_head_line(wxTextCtrl& ctrl, int step);
        void update_dump(wxTextCtrl& ctrl, const std::vector<char>& raw_buffer, int step);
};


#endif //__hexray__
