/**
 * @file hexray.h
 * @brief Header definition for the HexRay binary viewer module.
 *
 * This file declares the HexRay class, which provides the core functionality
 * for the hex viewer application using the wxWidgets library. It defines
 * essential constants for the display, including the number of columns
 * (HEXRAY_COLS) and the default step size (HEXRAY_DEF_STEPS).
 *
 * @author Corrado Ubezio
 * @date 2026
 * @version 0.1.0
 */
#ifndef __hexray__
#define __hexray__

#pragma once

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"

#include <vector>
#include <string>

#define HEXRAY_COLS 32
#define HEXRAY_DEF_STEPS 1 // step to 1, 2, or 4

class HexRay
{
public:
    // Constructor: Initializes the object when it is created
    HexRay();

    // Destructor
    virtual ~HexRay();

    std::vector<char> get_raw(std::string input_file_path);
    void build_head_line(wxTextCtrl &ctrl, int step);
    void update_dump(wxTextCtrl &ctrl, const std::vector<char> &raw_buffer, int step);
    int get_step_size(int index);
};

#endif //__hexray__
