/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	A lightweight binary file viewer
 * 				created using wxWidgets GUI library.
 * Author:      Corrado UBEZIO
 * Created:     2026
 * Copyright:   Corrado UBEZIO
 * License:   	MIT
 *
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
    SetTopWindow(new MainFrame(NULL));
    GetTopWindow()->Show();

    // true = enter the main loop
    return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow *parent) : MainFrameBase(parent)
{
    SetTitle(PROJECT_NAME);
    SetIcon(wxICON(sample));
    SetStatusText("Select a file to view in binary mode");

    hexray = new HexRay();
}

MainFrame::~MainFrame()
{
}

void MainFrame::OnCloseFrame(wxCloseEvent &event)
{
    Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent &event)
{
    Destroy();
}

void MainFrame::OnWordSizeSelection(wxCommandEvent &event)
{
    refresh_dump(hexray->get_step_size(wordSizeCombo->GetSelection()));
}

void MainFrame::OnOpenClick(wxCommandEvent &event)
{
    // Select the file to dump
    wxString inputFilePath;
    wxFileDialog dlg(this, "Open File", "", "");
    if (dlg.ShowModal() == wxID_OK)
    {
        inputFilePath = dlg.GetPath();
    }
    else
    {
        return;
    }

    // Get selected file content
    hexray_raw = hexray->get_raw(inputFilePath.ToStdString());
    if (hexray_raw.empty())
    {
        wxMessageBox("Error: Could not read '" + inputFilePath + "' file.", "Error", wxOK | wxICON_ERROR, this);
        return;
    }

    // Finalize frame setup
    this->SetTitle(PROJECT_NAME " " + inputFilePath);
    SetStatusText(wxEmptyString);

    // Set hexadecimal dump area
    refresh_dump(hexray->get_step_size(wordSizeCombo->GetSelection()));

    // Ensure the sizer updates to accommodate the new space
    this->Layout();
}

void MainFrame::OnAboutClick(wxCommandEvent &event)
{
    wxMessageBox(wxString::Format(
                     "A lightweight binary file viewer\n\n"
                     "Framework: %s\n"
                     "OS: %s.\n"
                     "\nC/C++ compiler: %s v%s",
                     wxVERSION_STRING,
                     wxGetOsDescription(),
                     COMPILER_ID, COMPILER_VERSION),
                 "About " PROJECT_NAME " ver. " PROJECT_VERSION,
                 wxOK | wxICON_INFORMATION,
                 this);
}

void MainFrame::refresh_dump(int step_size)
{
    if (hexray_raw.empty())
    {
        return;
    }

    hexray->build_head_line(*dumpHeadLineCtrl, step_size);
    hexray->update_dump(*dumpTextCtrl, hexray_raw, step_size);
}
