/**
 * @file main.h
 * @brief Declarations for the binary file viewer application.
 *
 * This header file contains the declarations and definitions for the binary
 * file viewer application. It declares the interfaces with the wxWidgets library,
 * and provides the core functionality for reading, displaying, and analyzing binary files.
 *
 * @note The wxWidgets interfaces are generated by wxFormBuilder and declared
 *       in the gui.h source file.
 *
 * @author Corrado Ubezio
 * @date 2026
 * @version 0.1.0
 */
#ifndef __main__
#define __main__

// CMake configuration header
#include "config.h"

#include "hexray.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
public:
	virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

class MainFrame : public MainFrameBase
{
public:
	MainFrame(wxWindow *parent);
	virtual ~MainFrame();

	HexRay *hexray;
	std::vector<char> hexray_raw;

protected:
	// protected event handlers
	void OnCloseFrame(wxCloseEvent &event) override;
	void OnExitClick(wxCommandEvent &event) override;
	void OnWordSizeSelection(wxCommandEvent &event) override;
	void OnOpenClick(wxCommandEvent &event) override;
	void OnAboutClick(wxCommandEvent &event) override;

	void refresh_dump(int step_size);
};

#endif //__main__
