/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"
#include "hexray.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <cctype>

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	SetTopWindow( new MainFrame( NULL ) );
	GetTopWindow()->Show();

	// true = enter the main loop
	return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation 
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow *parent) : MainFrameBase( parent )
{
    SetIcon(wxICON(sample));
    SetStatusText("Binary File Viewer");
}

MainFrame::~MainFrame()
{
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
	Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
	Destroy();
}

void MainFrame::OnOpenClick(wxCommandEvent& event)
{
    // Open the file in binary mode and read its content
    wxString inputFilePath;
    //wxFileDialog dlg(this, "Open File", "", "All files (*.*) | *.*");
    wxFileDialog dlg(this, "Open File", "", "");
    if (dlg.ShowModal() == wxID_OK)
    {
        inputFilePath = dlg.GetPath();
    }
    else
    {
        return;
    }

    std::ifstream file(inputFilePath.ToStdString(), std::ios::binary | std::ios::ate);
    if (!file.is_open())
    {
        wxMessageBox("Error: Could not open '" + inputFilePath + "' file.", "Error", wxOK | wxICON_ERROR, this);
        return;
    }

    size_t fileSize = file.tellg();
    file.seekg(0, std::ios::beg);

    std::vector<char> buffer(fileSize);
    file.read(buffer.data(), fileSize);
    file.close();

    // Print the header
    std::stringstream head;
    head << "           ";  // add the initial padding
    for (size_t i = 0; i < HEXRAY_COLS; ++i)
    {
        // Force the hex formatting for the current index
        head << std::hex << std::uppercase << std::setw(2) << std::setfill('0') << i;

        // Add a space between bytes, but not after the last one
        if (i < (HEXRAY_COLS-1)) {
            if (i == (HEXRAY_COLS/2-1))
            {
                head << " - ";
            }
            else
            {
                head << " ";
            }
        }
    }
    headDataCtrl->Clear();
    headDataCtrl->AppendText(wxString(head.str()));
    headDataCtrl->Show(true);

    // Print the file as a 3-column hexdump: offset, 16 raw bytes, ASCII
    hexDataCtrl->Clear();
    for (size_t offset = 0; offset < fileSize; offset += HEXRAY_COLS)
    {
        unsigned int val32 = static_cast<unsigned int>(offset);
        wxString line = wxString::Format("%04X_%04X  ", (val32 >> 16), (val32 & 0xFFFF));
        wxString ascii;

        for (size_t i = 0; i < HEXRAY_COLS; ++i)
        {
            const size_t index = offset + i;

            if (index < fileSize)
            {
                const unsigned char byte = static_cast<unsigned char>(buffer[index]);
                line << wxString::Format("%02X ", byte);
                ascii << (std::isprint(byte) ? static_cast<char>(byte) : '.');
                if (i == (HEXRAY_COLS/2-1))
                {
                    line << "- ";
                    ascii << ' ';
                }
            }
            else
            {
                if (i == (HEXRAY_COLS/2-1))
                {
                    line << "     ";
                    ascii << "  ";
                }
                else
                {
                    line << "   ";
                    ascii << ' ';
                }
            }
        }

        line << "  " << ascii;
        hexDataCtrl->AppendText(line + "\n");
    }
    hexDataCtrl->Show(true);

    // Ensure the sizer updates to accommodate the new space
    this->Layout();
}

void MainFrame::OnAboutClick(wxCommandEvent& event)
{
    wxMessageBox(wxString::Format
                 (
                    "A lightweight binary file viewer\n\n"
                    "Framework: %s!\n"
                    "OS: %s.\n"
                    // output of 'gcc --version'
                    "MinGW-W64 x86_64-ucrt-posix-seh %d.%d.%d",
                    wxVERSION_STRING,
                    wxGetOsDescription(),
                    __GNUC__, __GNUC_MINOR__, __GNUC_PATCHLEVEL__
                 ),
                 "About HexRay",
                 wxOK | wxICON_INFORMATION,
                 this);
}
